receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        channel: '#all-chatops'
        api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
groups:
- name: kube-alerts
  rules:
  - alert: PodCrashLoop
    expr: kube_pod_container_status_restarts_total > 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Pod CrashLoop"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 5 times."
